### ISSUE TITLE
Error: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by kcibdev** [transitive-bullshit/chatgpt-twitter-bot#1]
Whenever i try to run the project using `npm run dev or npm run build` i keep getting this error
```
$ npm run build

> chatgpt-twitter-bot@0.0.1 prebuild
> run-s clean


> chatgpt-twitter-bot@0.0.1 clean
> del build

Could Not Find C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\build

> chatgpt-twitter-bot@0.0.1 build
> tsup

Error: Cannot find module 'node:path'
Require stack:
- C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\rollup\dist\shared\rollup.js
- C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\rollup\dist\rollup.js
- C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\tsup\dist\index.js
- C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\tsup\dist\chunk-PDM6VDW3.js
- C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\tsup\dist\cli-default.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\bright\Documents\Project\gtp-test\chatgpt-twitter-bot-main\node_modules\rollup\dist\shared\rollup.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

I already ran `npm install` to set everything but it's not working. Please how can i fix this issue

**Comment by transitive-bullshit** [comment]
What version of node.js?

**Comment by kcibdev** [comment]
Found the problem 
all i had to do was to update my node version from v14 to v18
