### ISSUE TITLE
Can you give me a little help on how to setup this bot?

### ISSUE THREAD

**Issue by RandomUserBTC** [transitive-bullshit/chatgpt-twitter-bot#8]
I've been trying to run it since yesterday but I can't succeed 😅
(Trying to guide myself using the AI, I'm still learning to code and for now I only know the basics of Python)

For now I have:
- Cloned the repository with _git clone_
- Changed directory with _cd chatgpt-twitter-bot_
- Used _npm install_ to install package.json dependencies
- After installing the dependencies I used the command _npm run build_ to compile
- After compiling I used the command _node build/index.js_

Are these the correct steps?
After running _node build/index.js_ it throws the error:

_Error: Dynamic require of "util" is not supported
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:382
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:1535
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:462
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:4405
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:462
    at file:///Users/bruno/chatgpt-twitter-bot/build/index.js:1:4967
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Node.js v19.3.0_

I believe I misconfigured the .env file, I'm having trouble understanding how to fill the ChatGPT credentials even though I read the entire NPM package readme

**Comment by transitive-bullshit** [comment]
Running `build` isn't necessary; it's more of a test step.

I'm using `tsx` to execute the script directly.

So `npm i -g tsx` and `tsx src/index.ts`

Assuming your `.env` is setup correctly. Getting all the required `.env` files is a huge pain unfortunately, especially twitter since we have to use both v1 and v2 of the APIs...

**Comment by 0xScriptK1d** [comment]
Ahh, I get it! 
I think I'm really missing something in the .env then
After running _npm i -g tsx_ and _tsx src/index.ts_ the terminal threw this error now:

(node:86611) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
refreshing twitter access token
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
    at __node_internal_ (node:internal/errors:713:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Emitted 'error' event on Keyv instance at:
    at KeyvRedis.<anonymous> (/Users/bruno/chatgpt-twitter-bot/node_modules/keyv/src/index.js:60:46)
    at KeyvRedis.emit (node:events:513:28)
    at KeyvRedis.emit (node:domain:489:12)
    at EventEmitter.<anonymous> (/Users/bruno/chatgpt-twitter-bot/node_modules/@keyv/redis/src/index.js:18:40)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at EventEmitter.silentEmit (/Users/bruno/chatgpt-twitter-bot/node_modules/ioredis/built/Redis.js:460:30)
    at Socket.<anonymous> (/Users/bruno/chatgpt-twitter-bot/node_modules/ioredis/built/redis/event_handler.js:189:14)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:525:35) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined'
}

Node.js v19.3.0
